= mkepr
:author: Marcos Cruz (programandala.net)
:revdate: 2015-12-17
:linkattrs:

// Copyright (C) 2015 Marcos Cruz (programandala.net)
//
// You may do whatever you want with this work, so long as you
// retain the copyright notice(s) and this license in all
// redistributed copies and derived works. There is no warranty.

== Description

mkepr is a command line tool that creates EPROM or Flash image
files containing files from the host system, ready to be used by
the Cambridge Z88 emulators
http://sourceforge.net/projects/zesarux/[ZESarUX, role="external"]
and
https://bitbucket.org/cambridge/ozvm[OZvm, role="external"].

http://programandala.net/en.program.mkepr.html[mkepr webpage].

== Requirements

mkepr has been written in Forth for
http://www.gnu.org/software/gforth/[Gforth, role="external"],
and needs two modules of the
http://irdvo.github.io/ffl/[Forth Foundation Library, role="external"].

Gforth and the Forth Foundation Library must be installed on the
system.

== Installation

Make sure the <mkepr.fs> is executable.  Then copy, move or
link it to a directory on your path.

Example for single-user installation:

----
chmod u+x mkepr.fs
ln mkepr.fs ~/bin/mkepr
----

Example for system-wide installation:

----
chmod ugo+x mkepr.fs
ln mkepr.fs /usr/local/bin/mkepr
----

== Usage

=== Syntax and options

----
Usage: mkepr [options] [files]

  -?, --help        show this help
      --version     show version info
  -f, --flash       create an Intel Flash card instead of an EPROM card
  -o, --output=FILE set output file; default: output.epr (or output.flash)
  -s, --size=KiB    set the card size; defaults: 32 KiB (EPROM), 512 KiB
                    (Flash)
  -q, --quiet       quiet mode: input files will not be listed
----

=== Usage examples

Note: mkepr must receive a literal list of filenames (including
their paths).  Sometimes a shell regular expression is enough,
but sometimes `find` must be used.

Create a default EPROM card containing all text files from the
current directory:

----
mkepr *.txt
----

Create a 128-KiB EPROM card containing all text files from the
current directory and all Forth sources from the _forth_
subdirectory (which will be preserved in the card):

----
mkepr --size=128 --output=forth.epr *.txt forth/*.fs
----

Create a 512-KiB Flash card containing all files of the current
directory and all subdirectories (the:

----
mkepr -f -s 512 -o /tmp/eprom.flash $(find  -name "*" -type f)
----

== Known issues

Filenames are checked according to the rules of the OZ file
system, and the program halts if any of their segments (sections
between slashes) is invalid. No attempt is made to adapt invalid
filenames, except removing the "./" prefix when present, right
before the actual checks. This means the input files must be on
the current directory. For example, the following command will
not work: `mkepr ../file.txt`.

// vim: tw=64
