= mkepr
:author: Marcos Cruz (programandala.net)
:revdate: 2015-12-12
:linkattrs:

// Copyright (C) 2015 Marcos Cruz (programandala.net)
//
// You may do whatever you want with this work, so long as you
// retain the copyright notice(s) and this license in all
// redistributed copies and derived works. There is no warranty.

== Description

mkepr is a command line tool that creates EPROM or Flash image
files containing files from the host system, ready to be used by
the Cambridge Z88 emulators
http://sourceforge.net/projects/zesarux/[ZESarUX, role="external"]
and
https://bitbucket.org/cambridge/ozvm[OZvm, role="external"].

http://programandala.net/en.program.mkepr.html[mkepr webpage].

== Requirements

mkepr has been written in Forth for
http://www.gnu.org/software/gforth/[Gforth, role="external"],
and needs two modules of the
http://irdvo.github.io/ffl/[Forth Foundation Library, role="external"].

Gforth and the Forth Foundation Library must be installed on the
system.

== Installation

Make sure <mkepr.fs> is executable. Example:

----
chmod u+x mkepr.fs
----

Copy, move or link it to a directory on your path. Example:

----
ln mkepr.fs ~/usr/local/bin/mkepr
----

== Usage

----
Usage: mkepr [options] [files]

  -?, --help        show this help
      --version     show version info
  -f, --flash       create an Intel Flash card instead of an EPROM card
  -o, --output=FILE set output file; default: output.epr (or output.flash)
  -s, --size=KiB    set the card size; defaults: 32 KiB (EPROM), 512 KiB
                    (Flash)
  -q, --quiet       quiet mode: input files will not be listed

Report bugs via programandala.net
----

// vim: tw=64
